version: "3"

services:
  cellxgene:
    build: .
    ports:
      - 5005:5005
    environment:
      CELLXGENE_BUCKET: cellxgene-gateway-example-set
      ANNOTATION_DIR: /opt/bitnami/data
      SYNC_ENABLED: "True"
    volumes:
      - ~/.aws:/.aws
      - ./airflow/logs:/opt/bitnami/airflow/logs
      - ./airflow/dags:/opt/bitnami/airflow/dags
      - ./app:/opt/bitnami/projects/app
      #- ./data:/root/data