ingress:
  enabled: false
  annotations: {}
proxy:
  service:
    type: ClusterIP
    annotations: {}
    ports:
      nodePort:
    loadBalancerIP:
  kubernetes:
    pod-wait-time: 600000
    namespace: default
  resources:
    requests:
      cpu: 1
      memory: 512Mi
    limits:
      cpu: 8
      memory: 5G
  title: "BioAnalyze - CellxGene Gateway"
  logo-url: https://github.com/dabble-of-devops-bioanalyze/biohub-info/raw/master/logos/BioHub_v1_logo_only-01.png
  container-log-path: ./container-logs
  authentication: none
  container-wait-time: 600000
  landing_page: /app-direct/cellxgene-gateway
  specs:
  - id: cellxgene-gateway
    port: 5005
    display_name: "CellxGene Gateway"
    container-image: dabbleofdevops/cellxgene-gateway:0.3.8-5
    container-wait-time: 600000
    heartbeat-enabled: true
    heartbeat-timeout: 600000
    container-memory-request: 2G
    container-memory-limit: 10G
    container-cpu-request: 1
    container-cpu-limit: 8
    service-account: my-service-account-1
    target-path: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
    container-env:
      GATEWAY_ENABLE_ANNOTATIONS: 1
      GATEWAY_ENABLE_BACKED_MODE: 1
      PROXY_FIX_FOR: 1
      PROXY_FIX_PROTO: 1
      PROXY_FIX_HOST: 1
      PROXY_FIX_PORT: 1
      PROXY_FIX_PREFIX: 1
      GATEWAY_IP: "0.0.0.0"
      GATEWAY_PORT: 5005
      # if you are using an s3 bucket you must have the credentials
      # cannot have s3:// prefix
      CELLXGENE_BUCKET: "cellxgene-gateway-example-set"
      SCRIPT_NAME: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH').replaceFirst('/$','')}"
    kubernetes-pod-patches: |-
      - op: add
        path: /spec/containers/0/env/-
        value:
            name: PROXY_ID
            value: "#{proxy.id}"

      - op: add
        path: /spec/containers/0/env/-
        value:
            name: PROXY_USERID
            value: "#{proxy.userId}"

      # in case the app has no volumes yet:
      - op: add
        path: /spec/volumes
        value:
          - name: cache-volume
            emptyDir: {}

      - op: add
        path: /spec/containers/0/volumeMounts
        value:
          - mountPath: /cache
            name: cache-volume
