apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:

{{- $values := include "shinyproxy.auth" . | mustFromJson -}}

{{- $_ := set $values "proxy" (omit $values.proxy "verticalPodAutoscaling" "image" "annotations" "labels" "nodeSelector" "resources" "service" "ldap" "kerberos" "keycloak" "openid" "saml" "social" "users") }}
{{- $_ := set $values.proxy.kubernetes "namespace" .Release.Namespace }}
{{- range .Values.proxy.specs }}
  {{- if not (index . "container-memory-request") }}
    {{- $_ := set . "container-memory-request" $.Values.appPod.resources.requests.memory }}
  {{- end }}
  {{- if not (index . "container-cpu-request") }}
    {{- $_ := set . "container-cpu-request" $.Values.appPod.resources.requests.cpu }}
  {{- end }}
  {{- if not (index . "container-memory-limit") }}
    {{- $_ := set . "container-memory-limit" $.Values.appPod.resources.limits.memory }}
  {{- end }}
  {{- if not (index . "container-cpu-limit") }}
    {{- $_ := set . "container-cpu-limit" $.Values.appPod.resources.limits.cpu }}
  {{- end }}
  {{- if  (index . "service-account") }}
    {{ $serviceAccount := get . "service-account" }}
    {{ $kubernetesPodPatches := get . "kubernetes-pod-patches" }}
    {{$_ := set . "kubernetes-pod-patches" (printf "- op: add\n  path: /spec/serviceAccountName\n  value: %s\n\n%s" $serviceAccount $kubernetesPodPatches ) }}
  {{- end }}
  {{- if (index . "labels") }}
    {{- $_ := set . "labels" (merge .labels (dict "z2sp.instance" $.Release.Name)) }}
  {{- else }}
    {{- $_ := set . "labels" (dict "z2sp.instance" $.Release.Name) }}
  {{- end }}
{{- end }}

  application.yml: |
  {{- $values | toYaml | nindent 4 }}
