apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-delete-user-pods
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "common.names.fullname" . }}-delete-user-pods
      labels:
        {{- include "shinyproxy.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "common.names.fullname" . }}
      containers:
      - name: delete-user-pods
        image: bitnami/kubectl:{{ .Capabilities.KubeVersion.Major }}
        args:
          - "delete"
          - "pods"
          - "-l"
          - "z2sp.instance={{ include "common.names.fullname" . }}"
          - "-n"
          - "{{ default .Release.Namespace }}"
