{{- if .Values.ingress.enabled -}}
{{- $releaseName  := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "shinyproxy-{{ .Release.Name }}"
  labels:
    {{- include "shinyproxy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.classname }}
  ingressClassName: {{ .Values.ingress.classname }}
  {{- end }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ default (index $.Values "proxy" "landing-page") $.Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: "shinyproxy-{{ $releaseName }}"
                port:
                  number: 8080
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}

