apiVersion: v1
kind: ServiceAccount
metadata:
  name: "shinyproxy-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "shinyproxy-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods","persistentvolumeclaims"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods/log"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "shinyproxy-{{ .Release.Name }}"
  namespace: {{ default .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: "shinyproxy-{{ .Release.Name }}"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: "shinyproxy-{{ .Release.Name }}"
