apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- $values := pick .Values "proxy" }}
{{- if .Values.auth.authSimpleEnabled }}
  {{- $_ :=  set $values.proxy "authentication" "simple" }}
  {{- $_ := set $values.proxy "users" .Values.auth.users }}
{{- else if .Values.auth.authNoneEnabled }}
  {{- $_ := set $values.proxy "authentication" "none" }}
{{- else if .Values.auth.authLDAPEnabled }}
  {{-  $_ := set $values.proxy "authentication" "ldap" }}
  {{- $_ := set $values.proxy "ldap" .Values.auth.ldap }}
{{- else if .Values.auth.authKerberosEnabled }}
  {{-  $_ := set $values.proxy "authentication" "kerberos" }}
  {{- $_ := set $values.proxy "kerberos" .Values.auth.kerberos }}
{{- else if .Values.auth.authKeyCloakEnabled }}
  {{-  $_ := set $values.proxy "authentication" "keycloak" }}
  {{- $_ := set $values.proxy "keycloak" .Values.auth.keycloak }}
{{- else if .Values.auth.authOpenIDEnabled }}
  {{-  $_ := set $values.proxy "authentication" "openid" }}
  {{- $_ := set $values.proxy "openid" .Values.auth.openid }}
{{- else if .Values.auth.authSAMLEnabled }}
  {{-  $_ := set $values.proxy "authentication" "saml" }}
  {{- $_ := set $values.proxy "saml" .Values.auth.saml }}
{{- else if .Values.auth.authSocialEnabled }}
  {{-  $_ := set $values.proxy "authentication" "social" }}
  {{- $_ := set $values.proxy "social" .Values.auth.social }}
{{- else if .Values.auth.authWebServiceEnabled }}
  {{-  $_ := set $values.proxy "authentication" "webservice" }}
  {{- $_ := set $values.proxy "webservice" .Values.auth.webservice }}
{{- end }}
{{- $_ := set $values "proxy" (pick $values.proxy "ldap" "kerberos" "keycloak" "openid" "saml" "social" "users") }}
  secrets.json: {{ $values | toJson | b64enc | quote }}