apiVersion: v1
kind: Service
metadata:
  # Updating the svc name to include the release
  name: "shinyproxy-{{ .Release.Name }}"
  labels:
    {{- include "shinyproxy.labels" . | nindent 4 }}
  {{- if .Values.proxy.service.annotations }}
  annotations:
    {{- .Values.proxy.service.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}

  {{- if and .Values.proxy.service.clusterIP (eq .Values.proxy.service.type "ClusterIP") }}
  clusterIP: {{ .Values.proxy.service.clusterIP }}
  {{- end }}

  {{- if .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  selector:
      {{- include "shinyproxy.selectorLabels" . | nindent 6 }}
  ports:
    - port: 80
      targetPort: 8080
      {{- if .Values.proxy.service.ports.nodePort }}
      nodePort: {{ .Values.proxy.service.ports.nodePort }}
      {{- end }}

