{{- if .Values.verticalPodAutoscaling.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  labels:
    {{- include "shinyproxy.labels" . | nindent 4 }}
  name: "shinyproxy-{{ .Release.Name }}-app-vpa"
spec:
  # recommenders field can be unset when using the default recommender.
  # When using an alternative recommender, the alternative recommender's name
  # can be specified as the following in a list.
  # recommenders:
  #   - name: 'alternative'
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: "shinyproxy-{{ .Release.Name }}"
  resourcePolicy:
    {{- toYaml .Values.verticalPodAutoscaling.resourcePolicy | nindent 4 }}
{{- end }}