name: Build and Push CellxGene Gateway Docker image
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Job Environment Variables
      run: |-
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        echo "CALVER=${CALVER}" >> $GITHUB_ENV
        echo "SHA7=${SHA7}" >> $GITHUB_ENV
    - uses: mikefarah/yq@v4.16.2
      id: yq
      with:
        cmd: yq eval '.appVersion' charts/cellxgene-gateway/Chart.yaml
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: images/cellxgene-gateway
        push: true
        build-args: |
          CELLXGENE_GATEWAY_VERSION=${{ steps.yq.outputs.result }}
        tags: |
          dabbleofdevops/cellxgene-gateway:${{ steps.yq.outputs.result }},dabbleofdevops/cellxgene-gateway:${{env.SHA7}}
