name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        # with:
        #   version: v3.4.0

      - name: Helm Dependency update
        run: |

          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add bioanalyze https://dabble-of-devops-bioanalyze.github.io/helm-charts/
          helm repo update

          PWD=$(pwd)

          cd charts/shinyproxy
          helm dep update
          helm dep build

          cd ../../charts/single-cell-cloud-lab
          helm dep update
          helm dep build

      # "arn:aws:ecr:us-east-1:018835827632:repository/shinyproxy"
      # "018835827632.dkr.ecr.us-east-1.amazonaws.com/helm-shinyproxy"
      # 018835827632.dkr.ecr.us-east-1.amazonaws.com/helm-cellxgene-gateway
      # Helm chart name must be the same as the repo name
      # 018835827632.dkr.ecr.us-east-1.amazonaws.com/cellxgene-gateway
      # 018835827632.dkr.ecr.us-east-1.amazonaws.com/shinyproxy
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: List packages
        run: |-
          ls -lah .cr-release-packages

      # Helm chart name must be the same as the repo name
      # 018835827632.dkr.ecr.us-east-1.amazonaws.com/cellxgene-gateway
      # 018835827632.dkr.ecr.us-east-1.amazonaws.com/shinyproxy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Upload to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          # REPO: 018835827632.dkr.ecr.us-east-1.amazonaws.com
          REPO: 709825985650.dkr.ecr.us-east-1.amazonaws.com
          IMAGE: 709825985650.dkr.ecr.us-east-1.amazonaws.com/dabble-of-devops/
          HELM_EXPERIMENTAL_OCI: "1"
        run: |-

          aws ecr get-login-password \
              --region us-east-1 | helm registry login \
              --username AWS \
              --password-stdin ${REPO}

          find .cr-release-packages \
            -name 'shinyproxy*.tgz' | xargs -I {} helm push {} oci://${REPO}/

          find .cr-release-packages \
            -name 'single-cell-cloud-lab*.tgz' | xargs -I {} helm push {} oci://${REPO}/

      - name: Describe images
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          # REPO: 018835827632.dkr.ecr.us-east-1.amazonaws.com
          # REPO: 709825985650.dkr.ecr.us-east-1.amazonaws.com
          REPO: 709825985650.dkr.ecr.us-east-1.amazonaws.com/dabble-of-devops/
          HELM_EXPERIMENTAL_OCI: "1"
        run: |-
          aws ecr describe-images \
            --repository-name single-cell-cloud-lab \
            --region us-east-1

          aws ecr describe-images \
            --repository-name shinyproxy \
            --region us-east-1
