name: Build and push Docker image
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Job Environment Variables
      run: |-
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
    - uses: mikefarah/yq@v4.16.2
      id: yq
      with:
        cmd: yq eval '.appVersion' charts/shinyproxy/Chart.yaml
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: images/shinyproxy
        push: true
        build-args: |
          SHINYPROXY_VERSION=${{ steps.yq.outputs.result }}
        tags: |
          dabbleofdevops/shinyproxy:${{ steps.yq.outputs.result }},dabbleofdevops/shinyproxy:${{env.SHA7}}
