name: Build and Push ShinyProxy Docker image

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run changed-files
        id: changed-docker
        uses: tj-actions/changed-files@v13.1
        with:
          files: "images/shinyproxy/**"

      - uses: mikefarah/yq@v4.16.2
        if: steps.changed-docker.outputs.any_changed == 'true'
        id: yq
        with:
          cmd: yq eval '.appVersion' charts/shinyproxy/Chart.yaml

      - uses: docker/setup-buildx-action@v1
        if: steps.changed-docker.outputs.any_changed == 'true'

      - uses: docker/login-action@v1
        if: steps.changed-docker.outputs.any_changed == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Job Environment Variables
        if: steps.changed-docker.outputs.any_changed == 'true'
        run: |-
          CALVER="$( date -u '+%Y.%m.%d' )"
          SHA7="${GITHUB_SHA::7}"
          VERSION="${{ steps.yq.outputs.result }}"

          echo "CALVER=${CALVER}" >> $GITHUB_ENV
          echo "SHA7=${SHA7}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and Push
        if: steps.changed-docker.outputs.any_changed == 'true'
        run: |-
          make VERSION=${VERSION} SHA=${SHA7} docker/build
          make VERSION=${VERSION} SHA=${SHA7} docker/push
